name: JA

on:
  push:
    paths:
      - ".github/workflows/ja.yaml"
      - "site/ja/**"
      - "tools/ja/**"

jobs:
  proofreading-ja:

    runs-on: ubuntu-latest

    env:
      REDPEN_VERSION: "1.10.1"

    strategy:
      matrix:
        dir:
          - site/ja/guide
          - site/ja/js
          - site/ja/lite
          - site/ja/probability
          - site/ja/r1
          - site/ja/tfx
          - site/ja/tutorials
          - site/ja/xla

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Download RedPen
        run: |
          wget https://github.com/redpen-cc/redpen/releases/download/redpen-${REDPEN_VERSION}/redpen-${REDPEN_VERSION}.tar.gz
          tar xvf redpen-${REDPEN_VERSION}.tar.gz
          cp tools/ja/logback.xml redpen-distribution-${REDPEN_VERSION}/conf/logback.xml

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.6"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter

      - name: Run proofreading tool
        run: |
          export PATH="redpen-distribution-${REDPEN_VERSION}/bin:${PATH}"
          ./tools/ja/bin/proofreading.sh ${{ matrix.dir }}
      
      # - name: Upload RedPen logs
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: RedPen logs
      #     path: tools/ja/redpen.log
